### ISSUE TITLE
Non-PCI? not PCI compliance?

### ISSUE THREAD

**Issue by badoet** [RazerMS/Seamless_Integration#12]
can help me clarify what is the non-PCI means here?
if its not PCI compliance, may i know why? and what option is available that is PCI compliance?

**Comment by apis17** [comment]
Hi badoet,

In short, MOLPay Seamless Integration (non-PCI) means MOLPay handle credit card information from our secured server and merchant **not required** to do PCI assessment to transact with MOLPay. However, it is recommended merchant know how to secure or protect themselves from internet threats.

For PCI compliance merchant, you can contact sales@molpay.com to get available options to suit your needs.
