### ISSUE TITLE
broken demo URL

### ISSUE THREAD

**Issue by cusxio** [RazerMS/Seamless_Integration#22]
Is there a place I can demo `Razer Seamless Integration`? Can't really know what it is just by reading the docs. 

All the demo links in the wiki is broken.

https://github.com/RazerMS/Seamless_Integration/wiki/Latest-Razer-Merchant-Services-Seamless-Integration-(non-PCI)

https://merchant.razer.com/seamless-demo-latest/index.html

**Comment by jimanx2** [comment]
Hello @cusxio, those links has been taken down temporarily from the wiki to prevent possible security issue. If you need the files, please write to support-sa@razer.com so we can share the files privately to you.
